export const gameDifficulties = {
	easy: {
		name: "Easy",
		cardImages: [
			{ id: 1, image: "/images/meteor.png" },
			{ id: 2, image: "/images/meteor.png" },
			{ id: 3, image: "/images/comet.png" },
			{ id: 4, image: "/images/comet.png" },
		],
		matchAudioFiles: ["/audio/wonderful.mp3"],
		gridProps: {
			xs: 6,
			spacing: 2,
			maxWidth: 400,
			marginTop: "0px",
			spacingForSmallScreen: 1,
			xsColumnsForSmallScreen: 6,
		},
		cardSize: {
			xs: { width: "70px", height: "70px" },
			sm: { width: "90px", height: "90px" },
			md: { width: "120px", height: "120px" },
		},
		cardImageSize: {
			xs: { width: "100%", height: "100%" },
			sm: { width: "100%", height: "100%" },
			md: { width: "100%", height: "100%" },
		},
		cardFrontImageSize: {
			xs: { width: "100%", height: "100%" },
			sm: { width: "100%", height: "100%" },
			md: { width: "100%", height: "100%" },
		},
		congratsRoute: "/congrats/easy",
	},
	normal: {
		name: "Normal",
		cardImages: [
			{ id: 1, image: "/images/meteor.png" },
			{ id: 2, image: "/images/meteor.png" },
			{ id: 3, image: "/images/moon.png" },
			{ id: 4, image: "/images/moon.png" },
			{ id: 5, image: "/images/comet.png" },
			{ id: 6, image: "/images/comet.png" },
		],
		matchAudioFiles: ["/audio/wonderful.mp3", "/audio/NiceJob.mp3"],
		gridProps: {
			xs: 4,
			spacing: 2,
			maxWidth: 500,
			marginTop: "0px",
			spacingForSmallScreen: 1,
			xsColumnsForSmallScreen: 6,
		},
		cardSize: {
			xs: { width: "60px", height: "60px" },
			sm: { width: "80px", height: "80px" },
			md: { width: "100px", height: "100px" },
		},
		cardImageSize: {
			xs: { width: "100%", height: "100%" },
			sm: { width: "100%", height: "100%" },
			md: { width: "100%", height: "100%" },
		},
		cardFrontImageSize: {
			xs: { width: "100%", height: "100%" },
			sm: { width: "100%", height: "100%" },
			md: { width: "100%", height: "100%" },
		},
		congratsRoute: "/congrats/normal",
	},
	hard: {
		name: "Hard",
		cardImages: [
			{ id: 1, image: "/images/earth.png" },
			{ id: 2, image: "/images/earth.png" },
			{ id: 3, image: "/images/jupiter.png" },
			{ id: 4, image: "/images/jupiter.png" },
			{ id: 5, image: "/images/mars.png" },
			{ id: 6, image: "/images/mars.png" },
			{ id: 7, image: "/images/mercury.png" },
			{ id: 8, image: "/images/mercury.png" },
			{ id: 9, image: "/images/neptune.png" },
			{ id: 10, image: "/images/neptune.png" },
			{ id: 11, image: "/images/saturn.png" },
			{ id: 12, image: "/images/saturn.png" },
		],
		matchAudioFiles: [
			"/audio/wonderful.mp3",
			"/audio/NiceJob.mp3",
			"/audio/Greatwork.mp3",
			"/audio/KeepItGoing.mp3",
			"/audio/Amazing.mp3",
		],
		gridProps: {
			xs: 3,
			spacing: 2,
			maxWidth: 600,
			marginTop: "0px",
			spacingForSmallScreen: 1,
			xsColumnsForSmallScreen: 4,
		},
		cardSize: {
			xs: { width: "60px", height: "60px" },
			sm: { width: "70px", height: "70px" },
			md: { width: "90px", height: "90px" },
		},
		cardImageSize: {
			xs: { width: "100%", height: "100%" },
			sm: { width: "100%", height: "100%" },
			md: { width: "100%", height: "100%" },
		},
		cardFrontImageSize: {
			xs: { width: "100%", height: "100%" },
			sm: { width: "100%", height: "100%" },
			md: { width: "100%", height: "100%" },
		},
		congratsRoute: "/congrats/hard",
	},
};
